// Generated by CoffeeScript 1.3.3
(function() {
  var $$, BetterSelect, build_element, renderOption, renderOptionGroup;

  $$ = function(html) {
    var elm;
    elm = document.createElement('div');
    elm.innerHTML = html;
    if (elm.children.length > 1) {
      return elm.children;
    } else {
      return elm.children[0];
    }
  };

  build_element = function(what, orig, obj) {
    var elm;
    elm = $$(_.template(obj["" + what + "_template"])(obj["process_" + what](orig)));
    elm.orig = orig;
    orig.better_version = elm;
    elm.better_select = obj;
    return elm;
  };

  renderOption = function(orig_option, bs) {
    var option;
    option = build_element('option', orig_option, bs);
    option.reset = function() {
      this.orig.selected = void 0;
      this.setAttribute('class', 'option');
      return bs.reset(this);
    };
    option.select = function() {
      this.orig.selected = 'selected';
      this.setAttribute('class', 'option selected');
      if (bs.select.getAttribute('class').indexOf('open') !== -1) {
        bs.toggle();
      }
      return bs.set_selected(this);
    };
    option.addEventListener('click', function() {
      return this.select();
    });
    bs.options.push(option);
    return option;
  };

  renderOptionGroup = function(orig_group, bs) {
    var child, group, _i, _len, _ref;
    group = build_element('option_group', orig_group, bs);
    _ref = orig_group.children;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      child = _ref[_i];
      group.appendChild(renderOption(child, bs));
    }
    bs.option_groups.push(group);
    return group;
  };

  BetterSelect = (function() {

    function BetterSelect(elm) {
      var child, children, method, selected, _i, _len, _ref,
        _this = this;
      selected = elm.selectedOptions;
      this.select = build_element('select', elm, this);
      _ref = this.select.children, this.selected_option = _ref[0], this.dropdown = _ref[1];
      this.default_selected = elm.selectedOptions;
      children = elm.children;
      for (_i = 0, _len = children.length; _i < _len; _i++) {
        child = children[_i];
        switch (child.tagName) {
          case 'OPTION':
            method = renderOption;
            break;
          case 'OPTGROUP':
            method = renderOptionGroup;
        }
        this.dropdown.appendChild(method(child, this));
      }
      this.default_selected[0].better_version.select();
      elm.parentNode.insertBefore(this.select, elm);
      elm.parentNode.insertBefore(elm, this.select);
      elm.style.display = 'none';
      this.selected_option.addEventListener('click', function() {
        return _this.toggle();
      });
    }

    BetterSelect.prototype.open = false;

    BetterSelect.prototype.toggle = function() {
      return this.select.setAttribute('class', (this.open = !this.open) ? 'select open' : 'select');
    };

    BetterSelect.prototype.reset = function(option) {
      return this.default_selected[0].better_version.select();
    };

    BetterSelect.prototype.set_selected = function(option) {
      return this.selected_option.innerHTML = option.innerHTML;
    };

    BetterSelect.prototype.options = [];

    BetterSelect.prototype.option_groups = [];

    BetterSelect.prototype.option_template = '<div class="option"><%= innerHTML %></div>';

    BetterSelect.prototype.option_group_template = '<div class="optgroup"><div class="option-group-label"><%= label %></div></div>';

    BetterSelect.prototype.select_template = '<div class="select"><div class="selected-option"></div><div class="dropdown"></div></div>';

    BetterSelect.prototype.process_option = function(option) {
      return option;
    };

    BetterSelect.prototype.process_option_group = function(option_group) {
      return option_group;
    };

    BetterSelect.prototype.process_select = function(select) {
      return select;
    };

    return BetterSelect;

  })();

}).call(this);
